"""add source_event_id to telemetry_records

Revision ID: 7e38f4f3d70b
Revises: e01c2724f67b
Create Date: 2026-09-20 10:58:01.088122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e38f4f3d70b'
down_revision: Union[str, None] = 'e01c2724f67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_records', sa.Column('source_event_id', sa.String(length=64), nullable=True))
    op.create_index('uq_telemetry_records_vehicle_source_event', 'telemetry_records', ['vehicle_id', 'source_event_id'], unique=True, postgresql_where=sa.text('source_event_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_telemetry_records_vehicle_source_event', table_name='telemetry_records', postgresql_where=sa.text('source_event_id IS NOT NULL'))
    op.drop_column('telemetry_records', 'source_event_id')
    # ### end Alembic commands ###