"""initial schema: vehicles and telemetry_records

Revision ID: e01c2724f67b
Revises: 
Create Date: 2026-09-20 09:48:42.359347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e01c2724f67b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('engine_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.create_table('telemetry_records',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('engine_load', sa.Float(), nullable=True),
    sa.Column('coolant_temperature', sa.Float(), nullable=True),
    sa.Column('oil_temperature', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.Column('intake_air_temperature', sa.Float(), nullable=True),
    sa.Column('throttle_position', sa.Float(), nullable=True),
    sa.Column('engine_runtime', sa.Float(), nullable=True),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_records_timestamp'), 'telemetry_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_records_vehicle_id'), 'telemetry_records', ['vehicle_id'], unique=False)
    op.create_index('ix_telemetry_records_vehicle_id_timestamp', 'telemetry_records', ['vehicle_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_records_vehicle_id_timestamp', table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_vehicle_id'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_timestamp'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###